# Generated by Django 4.2.24 on 2025-09-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tts', 'TTS'), ('recording', 'UserRecording')], max_length=16)),
                ('lang_code', models.CharField(default='ln', max_length=10)),
                ('text_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='audio/')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.item')),
            ],
        ),
    ]
